# NetworkParser Configuration File

analysis:
  bootstrap_iterations: 2000
  confidence_threshold: 0.99
  max_interaction_order: 3
  fdr_threshold: 0.01
  min_group_size: 5
  correction_method: fdr_bh

processing:
  max_workers: 16
  memory_efficient: true
  chunk_size: 1000

output:
  formats: ["text", "json", "xml"]
  include_matrices: true
  generate_plots: true

validation:
  cross_validation_folds: 5
  stability_threshold: 0.9
  min_bootstrap_support: 0.8

explainable_ai:
  annotate_features: true
  biological_context: true
  interaction_interpretation: true