[mypy]
files = network_parser
python_version = 3.10
ignore_missing_imports = True
follow_imports = skip
strict_optional = False
allow_redefinition = True
show_error_codes = True
cache_dir = /tmp/networkparser_mypy_cache
