#!/bin/bash
# =============================================================================
# NetworkParser validation configuration for the AFRO_TB train/test split.
# Edit values below. Settings only — each experiment script is self-contained.
# =============================================================================

# Repository root and Python executable. These defaults let the scripts run
# from any current working directory without requiring an editable install.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python}"

# --- Input paths ---
SPLIT_ROOT="/Users/nmfuphicsir.co.za/Documents/pHDProject/Data/AFRO_TB/subset_valid_hierarchy"
RAW_TRAIN_GENOMIC="${SPLIT_ROOT}/train"
RAW_TEST_GENOMIC="${SPLIT_ROOT}/test"
TRAIN_SAMPLE_MANIFEST="${SPLIT_ROOT}/train_samples.csv"
TEST_SAMPLE_MANIFEST="${SPLIT_ROOT}/test_samples.csv"

# The train/test folders are the current manifest-backed 80/20 split. The
# preparation script recreates a separately validated, disjoint symlink view
# from the authoritative manifests before each NetworkParser validation run.
CLEAN_SPLIT_ROOT="${SPLIT_ROOT}/networkparser_manifest_split"
TRAIN_GENOMIC="${CLEAN_SPLIT_ROOT}/train"
TEST_GENOMIC="${CLEAN_SPLIT_ROOT}/test"
# Authoritative phenotype table (source). prepare_inputs derives Lineage_family
# and writes META + EVALUATION_META under CLEAN_SPLIT_ROOT.
META_SOURCE="${META_SOURCE:-/Users/nmfuphicsir.co.za/Documents/pHDProject/Data/AFRO_TB/metadata/AFRO_dataset_meta_with_test_hierarchy.csv}"
META="${CLEAN_SPLIT_ROOT}/metadata_with_lineage_family.csv"
# Generated by 00_prepare_inputs.sh from META_SOURCE, restricted to held-out IDs.
EVALUATION_META="${CLEAN_SPLIT_ROOT}/test_evaluation_metadata.csv"
# Resume hierarchy training when node_summary.json + model already exist.
HIERARCHY_RESUME="${HIERARCHY_RESUME:-0}"
# Global (cohort-wide) fallbacks: none | terminal | lineage | legacy | comma list of labels
# Default none = path-local hierarchy only (+ optional parent-conditioned terminal fallbacks).
GLOBAL_FALLBACK_LABELS="${GLOBAL_FALLBACK_LABELS:-none}"
REF="/Users/nmfuphicsir.co.za/Documents/pHDProject/Code/VCF_2_Matrix/ref/H37Rv.gbk"

# Identity contract for the configured AFRO VCFs and H37Rv GenBank file.
# The AL123456.3 and NC_000962.3 H37Rv sequences are identical, but annotation
# deliberately requires the exact ID recorded by the configured GenBank file.
EXPECTED_VCF_CONTIG="M.tuberculosis_H37Rv"
EXPECTED_REFERENCE_BUILD="AL123456.3"

# --- Output root ---
BASE_OUT="${BASE_OUT:-/Users/nmfuphicsir.co.za/Documents/pHDProject/Results/All_VCFs/chi2_fdr}"

# --- Training / query ---
N_JOBS="${N_JOBS:-4}"
FILTER="${FILTER:-chi2_fdr}"
QUERY_INPUT_TYPE="${QUERY_INPUT_TYPE:-vcf}"
RANDOM_STATE="${RANDOM_STATE:-42}"

# AFRO VCF callability policy. These bcftools variant-only VCFs contain
# GT:PL:DP but no GQ field, so the general NetworkParser default GQ>=20 would
# classify every record as GQ_missing. The JSON explicitly disables that
# unavailable threshold and opts into absence-as-reference for this known
# variant-only callset. The same policy is passed to train, query, and CV.
NETWORKPARSER_CONFIG="${NETWORKPARSER_CONFIG:-${SCRIPT_DIR}/afro_vcf_config.json}"

# --- Leakage-aware cross-validation ---
# Uses TRAIN_GENOMIC only. Held-out TEST_GENOMIC is not used in CV.
RUN_LEAKAGE_AWARE_CV="${RUN_LEAKAGE_AWARE_CV:-0}"
CV_REPEATS="${CV_REPEATS:-5}"
CV_SPLITS="${CV_SPLITS:-5}"
CV_PANEL_SIZES="${CV_PANEL_SIZES:-100,200,500,1000}"
CV_ALGORITHM="${CV_ALGORITHM:-}"  # empty = use the normal model-selector pathway

# --- Panel annotation (post-training; inline at end of each 01–06 script) ---
# 1 = run annotate-panels after train/query/evaluate/(optional CV)
# 0 = skip
RUN_PANEL_ANNOTATION="${RUN_PANEL_ANNOTATION:-1}"

# WHO 2023 catalogue converted to exact H37Rv Position/Ref/Alt records.
# It contains only WHO "associated with resistance" and interim-associated rows.
CATALOGUE="/Users/nmfuphicsir.co.za/Documents/pHDProject/Data/AFRO_TB/metadata/resistance_catalogue.tsv"

# Optional CV stability table (Feature_ID + selection_frequency). Leave empty if unused.
# Tip: after CV, point this at validate_cv/.../cv_feature_stability.tsv if desired.


STABILITY_TSV=""

# Keep markers with selection_frequency >= this value when STABILITY_TSV is set.
MIN_STABILITY=0.0
